language: python
python:
  - "3.4"
  - "3.5"

virtualenv:
  system_site_packages: true

# command to install dependencies
install: 
  - pip3 install -r requirements.txt --use-mirrors

# run tests
script: 
  - python3 run_tests.py
