language: python
sudo: true

python:
  - "3.4"
  - "3.5"

# before install
before_install:
  - sudo apt-get install libcapstone-dev python-capstone

# command to install dependencies
install: 
  - pip3 install -r requirements.txt 

# run tests
script: 
  - python3 run_tests.py
